cxx.std = experimental

cxx.features.symexport = true

using cxx

cxx{*}: extension = cpp
hxx{*}: extension = hpp
mxx{*}: extension = mpp


./ : exe{hello} lib{print}

exe{hello} : hello/{hxx cxx}{*} libs{print}

lib{print} : print/{cxx mxx}{*}

