cxx.std = 17

using cxx

cxx{*}: extension = cpp
hxx{*}: extension = hpp

if ($cxx.target.class != 'windows')
{
    cxx.libs += -lpthread
}

./ : exe{hello} lib{print}

exe{hello} : hello/{hxx cxx}{*} liba{print}

lib{print} : print/{cxx hxx}{*}
lib{print} : cxx.export.poptions =+ "-I$src_root"

for test_cpp : cxx{tests/print/**}
{
    test_name = $name($test_cpp)
    ./ : exe{$test_name} : $test_cpp liba{print}
}

