cxx.std = 17

using cxx

cxx{*}: extension = cpp
hxx{*}: extension = hpp

# Link with pthread on non-Windows
# if ($cxx.target.class != 'windows')
# { cxx.libs += -lpthread }

exe{hello} : hello/{hxx cxx}{*} liba{print}

lib{print} : print/{cxx hxx}{*}
lib{print} : cxx.export.poptions =+ "-I$src_root"

# All cpp files in test/print are test executables.
# for test_cpp : tests/print/cxx{**}
# {
#     test_name = $name($test_cpp)
#     ./ : exe{$test_name} : $test_cpp liba{print}
# }

